name: GitHub Issue notifications

on:
  issue_comment:
  issues:

jobs:
  issue-notification:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - name: Send Notification on Slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "action": "ACTION",
            "issueNumber": "NUMBER"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        NUMBER: ${{ github.event.issue.number }}
        ACTION: ${{ github.event.number }}