name: GitHub Issue notifications

on: [issue_comment,issues]

jobs:
  issue-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notifications on Slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        payload: |
          {
            "action": $ACTION_NAME,
            "eventName": $EVENT_NAME,
            "issueNumber": $ISSUE_NUMBER,
            "issueTitle": $ISSUE_TITLE
          }
      env:
        ACTION_NAME: ${{ github.event.action }}
        EVENT_NAME: ${{ github.event_name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}