name: GitHub Issue notifications

on: [issue_comment,issues]

jobs:
  issue-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notifications on Slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        payload: |
          {
            "action": "actionName",
            "issueNumber": "issueNumber"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}